language: ruby

ruby:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"

before_install:
  - env
  - lsb_release -a
  - uname -a
  - sudo apt-get -qq update

install:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml41+opam11
  - sudo apt-get -qq update
  - sudo apt-get -qq install opam ocaml ocaml-native-compilers camlp4-extra
  - export OPAMYES=1
  - opam init
  - opam install -y omake ounit extlib
  - eval `opam config env`
  - which omake

  - git clone https://github.com/jubatus/jubatus.git jubatus_server
  # jenerator
  - mkdir -p ~/bin
  - pushd jubatus_server/tools/jenerator && omake && PREFIX=~/ omake install && popd

  - sudo sh -c "echo 'deb http://download.jubat.us/apt binary/' > /etc/apt/sources.list.d/jubatus.list"
  - sudo apt-get -qq update
  - sudo apt-get -qq install jubatus --force-yes

  # for jubatus-ruby-client
  - bundle install

#branches:
#  only:
#    - master
#    - develop

script:
  - PATH=~/bin:${PATH} ./generate.sh
  - source /opt/jubatus/profile
  - rake test
  - rake integration_test
